.github/workflows/build.yml
I have added a workflow to build your repo using Github Actions.
It may be of interest to you...
=> CI: Build nuki_hub using Github Actions

CMakeLists.txt, MqttReceiver.h, Network.cpp, Network.h, NetworkLock.cpp, NetworkLock.h, NetworkOpener.cpp, NetworkOpener.h, PreferencesKeys.h, PresenceDetection.cpp, PresenceDetection.h, Version.h, WebCfgServer.cpp, WebCfgServer.h, main.cpp
Move shared network code into a common class
=> Refactor network

Network.cpp
Typos corrected:
- stat_cla vs state_cla
- dBm vs dBsm
=> Fixed state_class abbreviation and BT unit of measure

README.md
Add details on current support of KeyPad 2.0
(according to https://community.home-assistant.io/t/nuki-hub-firmware-for-the-esp32/417572/225)
=> KeyPad 2.0 notes

Ota.cpp, Ota.h, WebCfgServer.cpp, WebCfgServer.h
=> fix #123 - No autoforward after initiated update

Network.cpp
-Add Home Assistant auto discovery topics for Unlatch, Lock 'n' Go and Lock 'n' Go with Unlatch buttons. Closes #284 and #231
=> Add Home Assistant Auto Discovery buttons

Docker/Dockerfile, Docker/README.md, Docker/build_with_docker.sh
Since configure the toolchain is a little bit difficult, I prepared a script to build using docker.
=> add docker build script

Network.cpp
=> Make Opener Sound Level a configurable number in HA

WebCfgServer.cpp
Closes #304 
Note: Compiles without issue,  but untested as I don't own an Opener
=> Show continuous mode state in WebCfg

Network.cpp
As discussed on Discord.  Fix for functionality introduced in #296
=> Fix Home Assistant Continuous mode switch

README.md
add some Info about M5Stack PoESP32 antenna.
=> Update README.md (add M5Stack PoESP32 Info)

README.md, src/MqttTopics.h, src/NetworkLock.cpp, src/NetworkLock.h, src/NetworkOpener.cpp, src/NetworkOpener.h, src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp
=> Extend keyturner state and publish Nuki device status updated

.github/workflows/build.yml, src/Config.h, src/MqttTopics.h, src/Network.cpp, src/WebCfgServer.cpp, src/main.cpp
Adds Github run id, number and attempt as build number to MQTT, info page and Home Assistant sensor
Run ID (first number before the dot) can be used to open the specifc run on GH with: 
https://github.com/technyon/nuki_hub/actions/runs/$RUN_ID
e.g.
https://github.com/technyon/nuki_hub/actions/runs/9225076087
=> Add build number

src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp
=> Fix Unpair

src/NetworkOpener.cpp, src/NetworkOpener.h, src/NukiOpenerWrapper.cpp
Based on https://github.com/technyon/nuki_hub/commit/11f43c64b489585a588ac96e1d1996894460cffb by @technyon 
Closes #298
=> Add HA keypad for opener

README.md, src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp
=> Fix opener config

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md, .github/config.yml, .github/issue-close-app.yml, .github/workflows/stale-actions.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md
=> GitHub standards, bots and templates (Stale bot, Issue/PR templates, Code of conduct, Security policy, Contributing)

src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp
**Related issue (if applicable):** None on  Github, bug reported on Discord by @mundschenk-at 
=> Fix operators

lib/WiFiManager/WiFiManager.h, src/NukiNetwork.cpp, src/NukiNetwork.h, src/NukiNetworkLock.cpp, src/NukiNetworkLock.h, src/NukiNetworkOpener.cpp, src/NukiNetworkOpener.h, src/networkDevices/WifiDevice.cpp
**Related issue (if applicable):** Possibly fixes #413
=> Fixes/Enhancement for MQTT and WiFi reconnect + network  timout + MQTT retain

.github/workflows/beta.yml, .github/workflows/build.yml, .github/workflows/nightly.yml, src/NukiNetwork.cpp, src/WebCfgServer.cpp
=> Show available OTA versions on Firmware update page

src/MqttTopics.h, src/NukiNetwork.cpp, src/NukiWrapper.cpp, src/NukiWrapper.h, src/WebCfgServer.cpp
As requested on Discord add some more (maintenance) Home Assistant auto discovery topics.
=> Add HA discovery topics

Docker/Dockerfile, Docker/build_with_docker_pio.sh, Docker/build_with_docker_pio_debug.sh, Makefile
**Related issue (if applicable):** fixes #449
=> Fix Docker/Makefile

src/NukiOpenerWrapper.cpp
**Related issue (if applicable):** fixes #438
=> Report correct result when reading the Opener config

src/NukiNetwork.cpp, src/NukiNetwork.h, src/NukiNetworkLock.cpp, src/NukiNetworkLock.h, src/NukiNetworkOpener.cpp, src/NukiNetworkOpener.h, src/NukiOpenerWrapper.cpp, src/NukiOpenerWrapper.h, src/NukiWrapper.cpp, src/NukiWrapper.h, src/PreferencesKeys.h, src/WebCfgServer.cpp, src/WebCfgServer.h, src/main.cpp, src/networkDevices/EthernetDevice.cpp, src/networkDevices/EthernetDevice.h, src/networkDevices/WifiDevice.cpp, src/networkDevices/WifiDevice.h
Various fixes and enhancements related to recent changes in #455  and #456.
=> Various fixes for recently introduced changes/features

clion/CMakeLists.txt, src/Config.h, src/NukiNetwork.cpp, src/NukiNetworkLock.cpp, src/NukiNetworkLock.h, src/NukiNetworkOpener.cpp, src/NukiNetworkOpener.h, src/NukiOfficial.cpp, src/NukiOfficial.h, src/NukiPublisher.cpp, src/NukiPublisher.h, src/NukiWrapper.cpp, src/NukiWrapper.h, src/PreferencesKeys.h, src/WebCfgServer.cpp, src/main.cpp
=> Refactor official Nuki MQTT support. Move offical-specific code into sepereate class.

src/NukiNetwork.cpp
- fix `availability topic` (should be a list, check discussion in #475)
- fix `stat_jammed` abbreviated topic (should be `stat_jam`)
- [] Only one feature/fix was added per PR and the code change compiles without warnings
- [] The code change is tested and works
=> Fix for availability and state_jammed topics

src/NukiNetwork.cpp
**Related issue (if applicable):** fixes #485
=> Fix opener electronic strike actuation in HA

src/Config.h, src/NukiNetwork.cpp, src/NukiNetwork.h, src/WebCfgServer.cpp, src/WebCfgServer.h, src/networkDevices/WifiDevice.cpp, src/networkDevices/WifiDevice.h
=> Improve Wifi connection and portal

src/Config.h, src/WebCfgServer.cpp
=> Prevent reboot loop on manual web request

src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp
=> Fix AllowedUntil

src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp, src/WebCfgServer.cpp
=> Fix for JSON commands

README.md, platformio.ini, src/Config.h, src/NukiNetwork.cpp, src/WebCfgServer.cpp, updater/platformio.ini
- [ x The code change is tested and works
=> Update pioarduino and enlarge mqtt stack size

README.md
Fix the topic for authorization changes
=> Fix authorization/action topic in README.md

src/Config.h, src/NukiOpenerWrapper.cpp, src/NukiOpenerWrapper.h, src/NukiWrapper.cpp, src/NukiWrapper.h, src/WebCfgServer.cpp, src/main.cpp
**Related issue (if applicable):** fixes #509
=> Minor fixes

src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp, src/main.cpp
**Related issue (if applicable):** fixes #472
=> More minor fixes

README.md, boards/nuki-esp32dev.json, platformio.ini, src/Config.h, src/NukiNetwork.cpp, src/NukiNetwork.h, src/NukiNetworkOpener.cpp, src/NukiOpenerWrapper.cpp, src/NukiOpenerWrapper.h, src/NukiWrapper.cpp, src/NukiWrapper.h, src/PreferencesKeys.h, src/WebCfgServer.cpp, src/main.cpp, updater/platformio.ini
=> Various fixes for HTTP, MQTT, PSRAM and Ring detection + Add Home assistant enable/disable checkbox

src/Config.h, src/PreferencesKeys.h, src/WebCfgServer.cpp, src/main.cpp, src/networkDevices/WifiDevice.cpp
=> WiFi + OTA fix

src/Config.h, src/WebCfgServer.cpp, src/WebCfgServer.h, src/networkDevices/WifiDevice.cpp
=> WiFI fixes (AP not opening, WiFi reconfigure not working)

src/Config.h, src/WebCfgServer.cpp
**Related issue (if applicable):** fixes #542
=> Fix custom ethernet PHY addr save

src/HomeAssistantDiscovery.cpp, src/NukiNetwork.cpp
**Related issue (if applicable):** fixes #540
=> Fix reset mqtt topics

src/HomeAssistantDiscovery.cpp
=> Fix HA reboot Nuki button

src/HomeAssistantDiscovery.cpp
=> Add battery charging

resources/config_version.py, resources/ota_manifest.py, src/Config.h, src/PreferencesKeys.h, src/WebCfgServer.cpp
=> Fix version math

src/Config.h, src/NukiNetwork.cpp, src/NukiNetwork.h, src/PreferencesKeys.h, src/WebCfgServer.cpp
**Related issue (if applicable):** fixes #567
=> Retain Input GPIO

src/Config.h, src/WebCfgServer.cpp, src/WebCfgServer.h, src/idf_component.yml, src/main.cpp
- Reduce used stack
- Improve BLE reliability
=> Reduce HTTP handlers and improve BLE

src/Config.h, src/PreferencesKeys.h, src/main.cpp
**Related issue (if applicable):** fixes #574
=> Fix single core devices

src/NukiOpenerWrapper.cpp, src/NukiOpenerWrapper.h, src/NukiWrapper.cpp, src/NukiWrapper.h, src/PreferencesKeys.h, src/WebCfgServer.cpp
=> Allow forcing ID, Keypad and Doorsensor availability in Advanced

src/Config.h, src/NukiNetwork.cpp, src/networkDevices/WifiDevice.cpp, src/networkDevices/WifiDevice.h
=> Improve WiFi

src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp, src/RestartReason.h
=> Reboot on BLE stuck disconnecting

src/WebCfgServer.cpp
=> Fix WiFi factory reset

README.md, src/Config.h, src/HomeAssistantDiscovery.cpp, src/PreferencesKeys.h, src/WebCfgServer.cpp
**Related issue (if applicable):** fixes #581
=> Improve device ID for HA discovery

src/main.cpp
=> Revert "chore: update log entry for HTTP_EVENT_ON_DATA"

src/Config.h, src/WebCfgServer.cpp
=> OTA to alternate (Quad/Octal) PSRAM S3 binary

src/Config.h, src/NukiOpenerWrapper.cpp, src/NukiOpenerWrapper.h, src/NukiWrapper.cpp, src/NukiWrapper.h, src/PreferencesKeys.h, src/WebCfgServer.cpp, src/main.cpp
=> Update NukiHub and Nuki device time using NTP

src/Config.h, src/NukiNetworkLock.cpp
=> Fix lock/opener config in regards  to keypadV2 and undocumented settings

src/Config.h, src/HomeAssistantDiscovery.cpp, src/NukiNetworkLock.cpp, src/NukiNetworkOpener.cpp, src/NukiOpenerWrapper.cpp, src/NukiWrapper.cpp, src/PreferencesKeys.h, src/WebCfgServer.cpp
=> Improve nuki_ble data processing + further HA device id fix

src/Config.h, src/HomeAssistantDiscovery.cpp, src/NukiNetwork.cpp
=> Fix endless reboot on webserver disable + Fix HA ID

platformio.ini, updater/platformio.ini
=> Pioarduino 3.1.1

clion/CMakeLists.txt, src/Config.h, src/networkDevices/Tlk110Definitions.h, src/networkDevices/W5500Definitions.h, src/util/NetworkDeviceInstantiator.cpp
=> Fix m5 poeunit

src/Config.h, src/WebCfgServer.cpp, src/enums/NetworkDeviceType.h, src/networkDevices/W5500Definitions.h, src/util/NetworkDeviceInstantiator.cpp, src/util/NetworkUtil.cpp
=> Add Waveshare ESP32-S3-ETH support

.github/workflows/release.yml, README.md, index.html, pio_package_post.py, resources/how-to-flash.txt, src/Config.h
=> Webflash enhancements

.github/workflows/beta.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, README.md, index.html
=> Improve Webflash

.github/workflows/release.yml, resources/next_version.py
=> Auto set next release version

src/Gpio.cpp, src/Gpio.h, src/NukiOpenerWrapper.cpp, src/NukiOpenerWrapper.h, src/NukiWrapper.cpp, src/NukiWrapper.h
=> add GPIO output for bluetooth communication error
