technyon/nuki_hub

- WebCfgServer.cpp
How about adding some simple CSS via CDN?
When accessing locally without internet it will just fail to fetch and display as it is now.
This is how the site is seen using this CSS:
> Apply CSS to WebCfgServer

- Network.cpp
- Network.h
- NetworkOpener.cpp
- NetworkOpener.h
- NukiOpenerWrapper.cpp
- NukiOpenerWrapper.h
- NukiWrapper.cpp
- NukiWrapper.h
- PreferencesKeys.h
- README.md
- WebCfgServer.cpp
Docs:
https://www.home-assistant.io/docs/mqtt/discovery/
https://www.home-assistant.io/integrations/lock.mqtt/
Initial implementation
- Reads uid & name from lock config
- Publish to HASS /config topic
- Input form to set/change homeassistant autodiscovery topic
- Delete MQTT retained messages when unpairing or disabling HASS discovery
- README update with instructions
> Add MQTT discovery for Home Assistant

- .github/workflows/build.yml
Fix #18
- ESP32 SDK is now installed using Arduino IDE instead of using arduino-cli
- Removed arduino-cli (no longer needed)
> Fix CI Workflow

- MqttTopics.h
- Network.cpp
Add nuki hub version to mqtt. I would like to use this in home assistant (alongside with Github integration for latest releases) to notify when there is a new release.
Note: I don't have the toolchain set up yet, so didn't compile this.
> Publish version once on startup

- Network.cpp
Sensors are read-only entities and thus `config` is an invalid category for them (new check in Home Assistant 2023.11.0)
> Fix sound level sensor category

- Network.cpp
- NukiWrapper.cpp
- networkDevices/EthLan8720Device.cpp
- networkDevices/EthLan8720Device.h
- networkDevices/NetworkDevice.h
- networkDevices/W5500Device.cpp
- networkDevices/W5500Device.h
- networkDevices/WifiDevice.cpp
- networkDevices/WifiDevice.h
Hi,
I've just fixed a typo in mqttDisconnect method name, the "c" was missing and fixed a double semicolon.
> fix misspelled mqttDisonnect to mqttDisconnect

- AccessLevel.h
- NukiOpenerWrapper.cpp
- NukiWrapper.cpp
- WebCfgServer.cpp
Adds an accesslevel where locking and unlocking (and Lock N' Go) is possible through MQTT but not unlatching or reconfiguration of the Nuki lock and Keypad.
Usage is European style door/lock with a knob on the outside where I don't want to be able to open the door through MQTT (reasons as described in #177) but do want my smart home application to lock/unlock the deadbolt based on geo-fencing (when I enter the general area of the lock my smart home application will remove the deadbolt so my keypad/fob/app/key than only needs to take care of the latch)
> Add Accesslevel "Lock and Unlock operation only"

- Network.cpp
- README.md
- WebCfgServer.cpp
- index.html
- main.cpp
> Consistant naming as Nuki Hub instead of NUKI Hub

- PreferencesKeys.h
- main.cpp
This PR puts in place a system for migrating config variables on first boot with a new version if that version changes the configuration scheme.
I'm working on more granular access control which will mean splitting the currently set access level to multiple new settings for users that are upgrading.
> Allow migrating configuration on updates that change configuration scheme

- WebCfgServer.cpp
Hide the new GitHub buttons on the /ota WebCfg page after uploading a binary.
> Hide GitHub buttons on OTA

- NukiOpenerWrapper.cpp
- NukiWrapper.cpp
As per the API (and as evident from using the Nuki App) the Nuki PIN is required to retrieve auth data from the lock.
There currently is no check in NukiWrapper::updateAuthData() or NukiOpenerWrapper::updateAuthData() to check if the security PIN is set.
Enabling Publish Auth Data without a PIN set will result in lockouts of not just Nuki Hub but all systems using the API because Nuki Hub tries to retrieve the auth data with a PIN of 0.
PR fixes this behaviour.
> Disable UpdateAuthData when no PIN is set

- MqttTopics.h
- Network.cpp
- NetworkOpener.cpp
New ring event introduced in #299 creates warnings in the Home Assistant log. 
PR should fix this behaviour.
> Prevent Home Assistant warnings on Ring Event

- Network.cpp
- Network.h
- PreferencesKeys.h
- WebCfgServer.cpp
The current implementation that shows the latest version on the WebCfg page sometimes produces empty or garbled text.
Example:
I'm not sure of the root cause, but saving the saving the latest version to the cfg when latest version changes makes sure that the latest version is always known and seems to fix this issue.
> Fix webcfg ota link

- Network.cpp
The Unlatch button added in #284 only works for the Lock and not for the Opener because the command that is sent to nuki(opener)/lock/action is harcoded to unlatch instead of unlatch for the lock and electronicStrikeActuation for the opener.
Thix PR fixes this and changes the name of the button to "Open" instead of "Unlatch" as previously discussed.
Closes #310
> Fix Home Assistant Unlatch button for opener

- Network.cpp
- README.md
Adds the following to Home Assistant discovery.
Switches:
- Auto Lock
- Auto Unlock
- Single/Double Lock
Buttons:
- Query lock state
- Query config
- Query battery
- Query keypad
- Query lock state command result
All added as disabled by default.
Completes #261
> Add query and config actions to Home Assistant discovery

- .github/workflows/build.yml
- Docker/Dockerfile
- MqttTopics.h
- Network.cpp
- NetworkLock.cpp
- NetworkLock.h
- NetworkOpener.cpp
- NetworkOpener.h
- NukiOpenerWrapper.cpp
- NukiOpenerWrapper.h
- NukiWrapper.cpp
- NukiWrapper.h
- README.md
Todo
Closes #280 
Adds all available keypad functions from the [API](https://developer.nuki.io/page/nuki-smart-lock-api-2/2/#heading--add-keypad-code) to Nuki Hub.
All available information from keypad codes (except codes themselves) is published to `keypad/json`
Example:
```
[
{
"codeId": 1234,
"enabled": 1,
"name": "Test",
"dateCreated": "2024-01-01 10:00:00",
"lockCount": 100,
"dateLastActive": "2024-04-12 10:00:00",
"timeLimited": 0,
"allowedFrom": "0000-00-00 00:00:00",
"allowedUntil": "0000-00-00 00:00:00",
"allowedWeekdays": [
"mon",
"tue",
"wed",
"thu",
"fri",
"sat",
"sun"
],
"allowedFromTime": "00:00",
"allowedUntilTime": "00:00"
}
]
```
Adds the ability to change all keypad codes settings by publishing to `keypad/actionJson`.
Result is published to `keypad/commandResultJson`. …
> Extend keypad

- README.md
- src/NukiOpenerWrapper.cpp
- src/NukiOpenerWrapper.h
- src/NukiWrapper.cpp
- src/NukiWrapper.h
Allows updating keypad codes (enable/disable, enable/disable time limited, change allowed times/weekdays) without knowing and/or sending the keypad code itself.
> Make the code optional when updating keypad using JSON

- README.md
- src/RestartReason.h
- src/WebCfgServer.cpp
- src/WebCfgServer.h
Needs #375 to be merged to work fully as intended.
> Add Factory Reset option

- src/WebCfgServer.cpp
Adding `Cache-Control` header to files, the browser will automatically skip download on each page visit.
> webcfg: cache static files

- README.md
- src/Network.cpp
- src/Network.h
- src/WebCfgServer.cpp
As requested by @mundschenk-at
> Add GL-S10

- boards/nuki-esp32-s3.json
- platformio.ini
Builds S3 for devices with 4MB instead of 8MB flash. Smaller flash size should work without problems on devices with more flash, but this does not work the other way around, even when the partition table fits within 4MB.
Tested without issue using both the webflash binary and separate binaries on a S3 with 16MB flash.
**Related issue:** fixes #401 fixes #397
> Change ESP32-S3 to 4MB build

- .github/workflows/build.yml
Release workflow fails with `updateOnlyUnreleased: true`
> Fix release workflow

- src/NukiOpenerWrapper.cpp
- src/NukiWrapper.cpp
In 8.35 when number of retries is set to 0 no commands will be executed (except lock actions)
**Related issue (if applicable):** fixes #406
> Fix nr of retries

- src/Config.h
- src/WebCfgServer.cpp
Allow updating to beta firmware by browsing to `http://NUKIHUBIP/autoupdate?beta`
Beta firmware to be placed at `https://github.com/technyon/nuki_hub/raw/master/ota/beta/nuki_hub_esp32[device].bin`
When this is merged in 8.36 it can be used in beta testing for 8.37
> Allow auto update to beta firmware

- .github/workflows/build.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
Allow creating a release using Github Actions without manually creating a tag
Release can be created by going to Github -> Actions -> Nuki Hub Release -> Run workflow -> Run workflow
Will create a tag and release based on the version number in Config.h and auto create release notes based on PR's since latest tag/release.
> Create release using Github Actions manual dispatch

- HYBRID.md
- src/NukiWrapper.cpp
- src/WebCfgServer.cpp
-Actually respect value of `Sending actions through official MQTT` in Hybrid mode (was in fact always enabled when hybrid mode was enabled)
-Remove setting `Retry actions through BLE` in Hybrid mode as this is not implemented at this time
> Hybrid mode fixes

- README.md
With "Bluetooth Pairing" disabled for a Nuki Lock, pairing Nuki Hub via button is not possible. Readme reflects this now.
> Add requirement for Nuki Lock pairing

- src/main.cpp
During OTA upgrade, this text is repeated on every event execution, causing lots of line entries.
Unless it has any other purpose, I suggest to shorten it with a dot `[.]` for every event match.
> chore: update log entry for HTTP_EVENT_ON_DATA

- README.md
- src/Config.h
- src/Gpio.cpp
- src/MqttTopics.h
- src/NukiNetwork.cpp
- src/NukiNetwork.h
- src/NukiNetworkLock.cpp
- src/NukiNetworkLock.h
- src/NukiNetworkOpener.cpp
- src/NukiOfficial.cpp
- src/NukiOfficial.h
- src/NukiOpenerWrapper.cpp
- src/NukiWrapper.cpp
- src/NukiWrapper.h
- src/PreferencesKeys.h
- src/WebCfgServer.cpp
- src/main.cpp
- src/networkDevices/EthernetDevice.cpp
- src/networkDevices/IPConfiguration.cpp
- src/networkDevices/NetworkDevice.cpp
- src/networkDevices/WifiDevice.cpp
- src/util/NetworkUtil.cpp
- Add Hybrid / official MQTT authName and context
- Add device type and update time setting to info page
- Clear some extra MQTT topics on boot
- Reboot lock on Hybrid failure option
- Improvements to logging
- Keypad improvements
> Various improvemnts and fixes

- clion/CMakeLists.txt
- src/Config.h
- src/NukiNetwork.cpp
- src/NukiOpenerWrapper.cpp
- src/NukiOpenerWrapper.h
- src/NukiWrapper.cpp
- src/NukiWrapper.h
- src/util/NukiRetryHandler.cpp
- src/util/NukiRetryHandler.h
The nuki wrapper classes have many occurences of while loops to retry communication. This PR wraps this into a single NukiRetryWrapper class to reduce code duplication. Also handles gpio pins associated with communication.
> Refactor retry handling
